### ISSUE TITLE
te_inst: format 3, subformat0 condistion: resync counter > max_resync, in Chapter 9

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#113]
When the **resync counter=max_resync** and **branch map not empty**, te_inst: format 0/1/2 is sent.
When the **resync counter > max_resync**, te_inst: format 3 subformat 0 is sent. 
When the **resync counter=max_resync** and **branch map empty**, no packet is sent based on the figure 2. 
What is the intention of the distinction? Can sync packet (te_inst: format 3 subformat 0) be sent once the resync counter=max_resync?

**Comment by IainCRobertson** [comment]
The fundamental requirement is to send a format 3 message when the resync counter exceeds the max_resync value.  However, if there are any unreported branches, these have to be sent before the format 3 is generated, otherwise this information will be lost.  So all that is happening here is that the cycle (or packet) before the format 3 is generated, the unreported branches are reported if there are any.

Iain

From: zhangdujiao ***@***.***>
Sent: 04 June 2024 09:58
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] te_inst: format 3, subformat0 condistion: resync counter > max_resync, in Chapter 9 (Issue #113)


When the resync counter=max_resync and branch map not empty, te_inst: format 0/1/2 is sent.
When the resync counter > max_resync, te_inst: format 3 subformat 0 is sent.
When the resync counter=max_resync and branch map empty, no packet is sent based on the figure 2.
What is the intention of the distinction? Can sync packet (te_inst: format 3 subformat 0) be sent once the resync counter=max_resync?

-
