### ISSUE TITLE
What is the qual_status value at qualified 0->1 condition 

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#122]
Format 3 subformat 3-Support packet should be issued when trace is enabled.
For the trace on due to qualified 0->1, what is the value of qual_status? Both the value in table seems not suitable..
What if the filter is not supported in TE? qual_status=00?

**Comment by IainCRobertson** [comment]
Qual_status will be 00 any time a support packet is issued and trace has not ended.  This is not dependent on whether filtering is supported or not.

Iain

From: zhangdujiao ***@***.***>
Sent: 24 June 2024 09:37
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] What is the qual_status value at qualified 0->1 condition (Issue #122)


Format 3 subformat 3-Support packet should be issued when trace is enabled.
For the trace on due to qualified 0->1, what is the value of qual_status? Both the value in table seems not suitable..
What if the filter is not supported in TE? qual_status=00?

-
