### ISSUE TITLE
Definition of exc_only in figure 9.1 is different from explanation above 

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#127]
description of exc_only in figure 9.1 only contains exception, and interrupt is not included.

**Comment by IainCRobertson** [comment]
Yes, that is a minor error in the diagram.  When the spec was initially being written, the term "exception" was used to cover both exceptions and interrupts.  Later this was replaced with the term "trap".  But it looks like this piece of text didn't get updated (likely because it's embedded in a diagram)

Iain

From: zhangdujiao ***@***.***>
Sent: 28 June 2024 10:20
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] Definition of exc_only in figure 9.1 is different from explanation above (Issue #127)


description of exc_only in figure 9.1 only contains exception, and interrupt is not included.

-

**Comment by zhangdujiao** [comment]
Got it, great to know!
