### ISSUE TITLE
The field width of branch_map in format 1

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#133]
Can the width of branch_map be fixed at 31bit, rather than determined by branches value, since the latter will need lots of registers for implementation.

**Comment by IainCRobertson** [comment]
No, this is not possible (at least, not whilst remaining compliant to the E-Trace standard).

In our implementation this doesn't cost any registers, but it does require muxes to correctly align the upper part of the trace packet payload.  Whilst the approach you suggest would reduce the muxing cost, it would significantly impact the encoding efficiency.

Iain

From: zhangdujiao ***@***.***>
Sent: 04 August 2024 04:46
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] The field width of branch_map in format 1 (Issue #133)


Can the width of branch_map be fixed at 31bit, rather than determined by branches value, since the latter will need lots of registers for implementation.

-
