### ISSUE TITLE
Does the tval comparison require itype = 1 or 2?

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#135]
When trTeCompPInput codes 2: tval, should the itype =1/2 be added in the if condition, since tval only valid when trap happens.
thanks!

**Comment by IainCRobertson** [comment]
Yes, tval should only be compared when itype is 1 or 2.

Iain

From: zhangdujiao ***@***.***>
Sent: 18 August 2024 07:31
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] Does the tval comparison require itype = 1 or 2? (Issue #135)


When trTeCompPInput codes 2: tval, should the itype =1/2 be added in the if condition, since tval only valid when trap happens.
thanks!

-

**Comment by zhangdujiao** [comment]
I see, so the itype =1 or 2 should also be added during ecause match in the filter

**Comment by IainCRobertson** [comment]
Yes, absolutely.

Iain

**Comment by zhangdujiao** [comment]
For trTeFilterMatchChoiceEcauseLow, "When trTeFilterMatchEcause field for filter #i is set, match all excepion causes for which the corresponding bit is set. If bit N is 1, then match if the ecause is N."
Does the "all excepion causes" means only exceptions? or both excep. and int. ?

**Comment by zhangdujiao** [comment]
Can we set 1 at multiple bit? like 'b001001 for trTeFilterMatchChoiceEcauseLow value

**Comment by IainCRobertson** [comment]
Yes you can set multiple bits. That’s why it’s a bit vector. ‘Choice’ in the name indicates it is multiple choice, allowing you to pick any combination you want.

Whether it matches interrupts, exceptions or both depends on whether you enable matching on the ‘int’ bit. If this is not enabled, it will match both, and if it is enabled it will match interrupts if the ‘value’ bit is 1, or exceptions if it’s 0.

Apologies for not using the exact field names but I’m on vacation without access to the spec.
________________________________

**Comment by zhangdujiao** [comment]
> Yes you can set multiple bits. That’s why it’s a bit vector. ‘Choice’ in the name indicates it is multiple choice, allowing you to pick any combination you want.

great! have a nice trip:)
