### ISSUE TITLE
Can multiple filters can be selected by trTeInstFilters[15:0]?

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#140]
Should trTeInstFilters select only one filter to use? 
or multiple filters, and final qualified result could be obtained through the AND or OR operation of the results of multiple filters？

**Comment by IainCRobertson** [comment]
No, it can select any number - that’s why it’s a bit vector with a bit per filter rather than an encoded filter number.  The final result is the OR of the selected filters.  So for example, you could trace if the instruction address was in the range (A < addr < B) or (C < addr < D) by using 2 filters with different ranges.  ANDing of conditions is done within a single filter (e.g. A < addr < B AND priv == 0).

Iain

From: zhangdujiao ***@***.***>
Sent: 04 September 2024 03:37
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] Can multiple filters can be selected by trTeInstFilters[15:0]? (Issue #140)


Should trTeInstFilters select only one filter to use?
or multiple filters, and final qualified result could be obtained through the AND or OR operation of the results of multiple filters？

-
