### ISSUE TITLE
Could the system support multiple SMEMs in SoC?

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#148]
For Coresight, usually one ETR is used in SoC. While, the RV spec doesn't define the number of SMEM. 
If we want to put TE and an SMEM near each hart, and trace data from every hart can be sent to target memory directly, rather than collect the trace data from every TEs to single SMEM.
Can this multiple SMEMs scheme be supported by RISC-V Spec?

**Comment by IainCRobertson** [comment]
There is nothing in either the E-Trace spec, the Unformatted Trace & Diagnostic Data Packet Encapsulation spec nor the about to be ratified Trace Common Control trace spec that would preclude either of these arrangements.

Iain

From: zhangdujiao ***@***.***>
Sent: 27 September 2024 03:38
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] Could the system support multiple SMEMs in SoC? (Issue #148)


For Coresight, usually one ETR is used in SoC. While, the RV spec doesn't define the number of SMEM.
If we want to put TE and an SMEM near each hart, and trace data from every hart can be sent to target memory directly, rather than collect the trace data from every TEs to single SMEM.
Can this multiple SMEMs scheme be supported by RISC-V Spec?

-

**Comment by zhangdujiao** [comment]
Thanks!
