### ISSUE TITLE
updiscon field in format0/1/2

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#150]
From the description of updiscon field: "and is also the instruction before an exception, privilege change or resync".
The exception here includes both exception and interrupt, or just exception.
The resync here means resync_cnt == max_resync, right?
Thanks!

**Comment by IainCRobertson** [comment]
Yes, it should really say "trap" rather than "exception".

Iain

From: zhangdujiao ***@***.***>
Sent: 09 October 2024 12:43
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] updiscon field in format0/1/2 (Issue #150)


From the description of updiscon field: "and is also the instruction before an exception, privilege change or resync".
The exception here includes both exception and interrupt, or just exception.
The resync here means resync_cnt == max_resync, right?
Thanks!

-
